Use sys/unix constants for ioctls
diskfs/go-diskfs pull request #128
Opened 2021-08-29 22:54 UTC by mepholic

This fixes functionality on multiple CPU architectures.

The previously hardcoded blksszGet and blkpbszGet values are the correct
ioctl values on only a few architectures. PowerPC, MIPS, and Sparc use
different bit layouts in their ioctls, so it's best to get these values
from the sys/unix library.

2021-08-30 08:16 UTC, deitch commented
Thanks @mepholic 

Actually, we originally had that, but had to hard-code it because it isn't available on every platform, notably Darwin. I have no idea why, but there it is.

If you can remove the `darwin` from the `// +build` line, and then create a separate `diskfs_darwin.go` with `// +build darwin` which contains the hard-coded, then I think we will be covered.

2021-08-30 08:18 UTC, deitch requested changes
As discussed in the comment, please remove `darwin` from building on `diskfs_unix.go`, create a separate `diskfs_darwin.go` and we should be good.

Alternatively, we could have a `diskfs_unix.go` that is for all, and move the constants `blksszGet` and `blkpbszGet` out of `diskfs.go` and into `constants_unix.go` and `constants_darwin.go`, leaving `diskfs_unix.go` unchanged.

I think I like the second option better - fewer changes, much less repetition - but whatever works.

2023-03-01 08:18 UTC, yadutaf commented
It looks like a variant of this PR was merged in the meantime. Indeed, the constants are used in `diskfs_unix.go`. Maybe this can be closed ?

2023-03-01 08:20 UTC, deitch commented
I think so. If it is needed, we always can reopen

2023-03-01 08:20 UTC, closed without merging