Add support for setting a FAT32 label
diskfs/go-diskfs pull request #154
Opened 2022-10-14 20:37 UTC by yadutaf

This adds a ``SetLabel()`` to the ``FileSystem`` interface. On SquashFS and ISO 9660, this method returns an error, as the filesystems are read-only.

For FAT32, this new method re-uses code that was previously in ``Create()`` and ``Create()`` is updated to call this new method at filesystem initialization time. Doing this required to initialize the ``fs`` structure earlier, before writing anything to the destination. Let me know if this refactoring is acceptable!

On top of this, the PR seizes the occasion to move the label reading logic closer to Windows and dosfstools' ``fatlabel`` behavior. That is, they read the label from the root directory rather than the bootsector. And, according to ``fatlabel``'s man page, Windows does not even write the label to the bootsector, which would cause go-diskfs to fail detecting it.

For the tests, I manually modified the fixture with "fatlabel" to include a label by default and updated the Readme. Was this the proper way of doing ?

2022-10-16 08:40 UTC, deitch commented
"I torture packets / containers."

😆

2022-10-16 08:56 UTC, deitch commented
Adding `SetLabel()` makes sense, and the returns from read-only filesystems are correct.

I don't mind terribly moving all of the "write to disk" from `fat32.Create()` to the end, as opposed to interspersed. Moving just one of them to its own function `writeBootSector()` but not the others - e.g. `writeFsis`, `writeFat` - is a bit unbalanced.

Having `SetLabel()` means you need to add the enforcement of the label format into there, so might as well take advantage and use the raw label in the `dos71EBPB` structure, although that would require changing the comment [here](https://github.com/diskfs/go-diskfs/blob/d704acd18db2dae47d0cbb2cbed5850016b13fc5/filesystem/fat32/dos71bpb.go#L51). 

> That is, they read the label from the root directory rather than the bootsector. And, according to fatlabel's man page

I am somewhat torn on this. For `SetLabel()`, I like what you did, i.e. write it to both places. For read, are there compatibility issues? I cannot recall the driver behind the original implementation, but I am pretty sure the logic was taken from how Linux does it. Do we run the risk that some tool will write it _only_ to the boot sector volume label, and this `Label()` read code will miss it? Is there some other construct that we can use to distinguish between _on-filesystem_ label and _on bootsector_ label?

> For the tests, I manually modified the fixture with "fatlabel" to include a label by default and updated the Readme. Was this the proper way of doing ?

Unfortunately, yes. I have not come up with a better way.

2022-10-16 09:01 UTC, deitch requested changes
A few small changes. This is pretty nice.

2022-10-16 09:01 UTC, deitch commented on filesystem/fat32/fat32.go
> +	// write the fsis
This part is unbalanced now. We have `writeBootSector()` to wrap writes, but not for the next several, where we write directly. It might be cleaner to have a `writeFsis()` and `writeFatTables()` as well.

2022-10-16 09:01 UTC, deitch commented on filesystem/fat32/fat32.go
> +		volumeLabel:           volumeLabel, // "NO NAME    "
If the `volumeLabel` now reflects just raw data as passed, and not an enforced 11 bytes, then we need to change the comment [here](https://github.com/diskfs/go-diskfs/blob/d704acd18db2dae47d0cbb2cbed5850016b13fc5/filesystem/fat32/dos71bpb.go#L51).

2022-10-16 09:01 UTC, deitch commented on filesystem/fat32/fat32.go
> +	// locate the filesystem root directory
All of this reads _solely_ from the volume label magic file on the filesystem, and drops reading the volume label on the boot sector. 

Is there a compatibility issue? Are there implementations that write solely there, and we will miss it? Should we read from magical file and fall back to volume label on boot sector, or is that wrong? Conversely, is there a separate construct for that label that we could use?

2022-10-17 21:39 UTC, yadutaf commented on filesystem/fat32/fat32.go
> +	// write the fsis
Done and integrated in `allocateSpace`

2022-10-17 21:42 UTC, yadutaf commented on filesystem/fat32/fat32.go
> +		volumeLabel:           volumeLabel, // "NO NAME    "
Thinking of it, the enforcement should be preserved to remain compatible with the specification and thus the comment should not change. Instead, I need to fix this line. A changed has been pushed to initialize this field to "NO NAME". The size enforcement is done in ``SetLabel()``.

2022-10-17 22:05 UTC, yadutaf commented
Thanks for the review! I like the suggestion of introducing ``writeFsis`` and ``writeFat`` in the same way as ``writeBootSector``; this is also the occasion to share more code with ``allocateSpace``. I pushed a new proposition with these changes in a dedicated refactoring commit.

Regarding the compatibility concern, I might be a little bit too optimistic here, but I was considering that Windows is the reference implementation while Linux is the main alternative implementation. On Linux, the kernel does not read nor writes the label. There was a proposition some times ago to introduce an `ioctl` for it, but it did not get merged. Thus, the reference Linux implementation is ``fatlabel`` and I followed carefully the advertised behavior.

If it proves to be problematic, future options could be:
* Add a fallback path on the bootsector, but we may end up with stranger consistency issues.
* Add a FAT32 specific helper to query the label from the boot sector.

Would it be acceptable this way ?

2022-10-18 13:26 UTC, deitch commented
So are you saying that:

1. Windows is the reference, which you implemented here in this PR.
2. Linux does not do anything with it in the kernel at all.
3. Linux does it in `fatlabel` (userspace), which follows your implementation.

If that is correct, then I think we can work with this. Going to take another look at the changes.

2022-10-18 13:28 UTC, deitch commented
Going to kick off CI. If it all passes, are you good to go?

2022-10-18 13:28 UTC, deitch submitted a review, later dismissed

2022-10-18 14:50 UTC, yadutaf commented
Oops, the lint. Sorry... Will push a fix this evening. Aside from this, good to.

2022-10-19 06:21 UTC, deitch approved these changes

2022-10-19 06:21 UTC, merged