feat: implement remove and rename feature for fat32, add new unit-tests
diskfs/go-diskfs pull request #233
Opened 2024-07-03 09:33 UTC by ludelion5

Sorry for the late PR. Here is my proposal to rename and remove files in fat32.

closes #191

2024-07-04 13:42 UTC, deitch reviewed
Overall, this looks great, and thank you.

In terms of naming, are these meant to be restricted just to _files_, or any structure (files, dirs, symlinks where supported, etc.)? I would think the latter, since CLI-level commands for the above in most OSes don't care. Same for linux `mv` / Windows `ren`.

So should these be `RemoveFile()` and `RenameFile()`, or just `Remove()` and `Rename()`?

On the other hand, in keeping with golang style, maybe these should parallel and be [`Remove()`](https://pkg.go.dev/os#Remove) and [`RemoveAll()`](https://pkg.go.dev/os#RemoveAll) and [`Rename()`](https://pkg.go.dev/os#Rename]?

2024-07-12 08:48 UTC, ludelion5 commented
Thanks for the feedback. I will look into your request and test, if the implementation will also work for symlinks and directories. If so, its a good idea to stick to your suggested naming-scheme.

Additionally I can check if the RemoveAll is easy to implement, I have to see if I can spare enough time for that feature.

2024-11-15 13:30 UTC, ludelion5 commented
Sorry for the late update on this PR.

We adapted our Rename and Remove methods to the new interface.

Additionally we have implemented the ability to remove empty directories and the renaming to already existing files (overwriting).
Currently, the renaming (move) works only in the same directory, this would require a deeper understanding of your `fs.allocateSpace`, I guess this method has to be called multiple times, depending on how many directory levels the file moves. We check if the base-dir is different and return an error.

2024-11-16 14:09 UTC, aol-nnov commented on filesystem/fat32/fat32.go
>  //nolint:revive // parameters will be used eventually
As the method got implemented, lint exception is not needed anymore here. Please remove it.

2024-11-17 07:38 UTC, deitch commented
> Currently, the renaming (move) works only in the same directory, this would require a deeper understanding of your fs.allocateSpace, I guess this method has to be called multiple times, depending on how many directory levels the file moves. We check if the base-dir is different and return an error

That certainly is enough for now. We go from "this is not implemented" to "this is partially implemented", which his an improvement. So thank you.

2024-11-17 07:41 UTC, deitch requested changes
Just the lint comment.

2024-11-17 10:32 UTC, ludelion5 commented
done

2024-11-17 14:17 UTC, deitch approved these changes

2024-11-17 14:22 UTC, deitch commented
Just some lint errors that need to be fixed.

2024-11-17 15:45 UTC, ludelion5 commented
`make lint` should now be satisfied

2024-11-17 15:46 UTC, deitch approved these changes

2024-11-17 15:47 UTC, merged

2024-11-17 15:47 UTC, deitch commented
Looks great, thanks!

2024-11-17 15:53 UTC, ludelion5 commented
are you planning to create a new tag as well?

2024-11-17 15:54 UTC, deitch commented
Yeah but let's wait for this one.

2024-12-17 14:32 UTC, ludelion5 commented
Do you have an estimation when a new tag is created?

2024-12-17 17:39 UTC, deitch commented
https://github.com/diskfs/go-diskfs/releases/tag/v1.5.0