FAT32: add functions to get File cluster chain and disk areas
diskfs/go-diskfs pull request #271
Opened 2024-12-03 00:22 UTC by nkraetzschmar

For some low-level filesystem operations it can be beneficial to both get the cluster chain of a given file as well as querying where exactly on disk the file contents reside.

Examples where such info might be useful:
- Perform secure erase
- Detect file fragmentation
- Pass Disk byte offset or LBA to a different tool that can work with it

This PR adds two functions, one to just expose the internal getClustersList via the File type.
The other to express the same info directly in disk areas, where each area is described by its starting byte and a length in bytes. (further conversion to disk sectors / LBA can be easily performed by the caller.)

2024-12-03 20:18 UTC, deitch requested changes
Looks good to me, and I appreciate the description of the use cases. Maybe add those to the docs (even just the inline), so someone looking at this in 6 or 12 months and wonders why we would expose such details, can see?

Also there is a linting error.

2024-12-09 16:12 UTC, nkraetzschmar commented
sorry for the delay, added the use cases to the inline docs and fixed the linter errors now

2024-12-09 18:15 UTC, deitch approved these changes

2024-12-09 18:15 UTC, merged

2024-12-09 18:15 UTC, deitch commented
No problem. Thanks for contributing.