Fix streaming fat32 file write
diskfs/go-diskfs pull request #65
Opened 2020-08-20 19:30 UTC by rtreffer

This PR (based on #64 ) fixes streaming fat32 file writes.

After each write the file offset should be advanced by the number of bytes written. see commit dd19876

2020-08-24 15:34 UTC, deitch commented
Will wait until we finish #64 to comment on this.

2020-08-24 21:04 UTC, rtreffer commented
@deitch I've reworked this PR on top of #69 which should be easier to review

2020-08-25 08:58 UTC, deitch commented
#69 is merged in, so this should be rebased. It will reduce the number of changes.

2020-08-25 09:01 UTC, deitch requested changes
Just needs a rebase and this can go in

2020-08-25 09:01 UTC, deitch commented on filesystem/fat32/file.go
> +	fl.offset = fl.offset + int64(totalWritten)
Personally, I think that Unix should have separate offsets for read and write. But we are not about to change 40+ years of history here, and we should stick to the standard, so this makes sense.

2020-08-25 18:05 UTC, rtreffer commented
freshly rebased

2020-08-26 07:28 UTC, deitch commented
Nothing like some fresh rebase with a mug of tea for breakfast. 😀

2020-08-26 07:28 UTC, deitch approved these changes

2020-08-26 07:28 UTC, merged